### ISSUE TITLE
 error CS5001: Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by ea-r1** [FizzerWL/Cs2hx#11]
Can't convert minimal console application for .NET 4.8

[ConsoleApp1.zip](https://github.com/FizzerWL/Cs2hx/files/13510519/ConsoleApp1.zip)

output:
`Cs2hx.exe /sln:..\ConsoleApp1.sln /config:Debug
C# to haXe Converter
See https://github.com/FizzerWL/cs2hx for full info and documentation.

Visual Studio intances: Visual Studio Professional 2022 -17.7.34024.191 C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin
Registered visual studio: Visual Studio Professional 2022 - 17.7.34024.191

Converting project ConsoleApp1...
Building...
Parsing...
Parsed in 00:00:00.0010595. Writing out haxe...
Haxe written out in 00:00:00.0075515

Exception:
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. 2 errors:
  warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
  error CS5001: Program does not contain a static 'Main' method suitable for an entry point
   at Cs2hx.Program.Build() in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Program.cs:line 69
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Go(Compilation compilation, String outDir, IEnumerable`1 extraTranslation, String ctorHelperName, HashSet`1 whitelist, Boolean buildFirst) in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Program.cs:line 57
   at Cs2hx.EntryPoint.Main(String[] args) in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\EntryPoint.cs:line 128
---> (Inner Exception #0) System.Exception: Build failed. 2 errors:
  warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
  error CS5001: Program does not contain a static 'Main' method suitable for an entry point
   at Cs2hx.Program.Build() in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Program.cs:line 69
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in C:\Users\user01\Haxe\Cs2hx-master-2\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---`

**Comment by FizzerWL** [comment]
This is a roslyn issue, see https://github.com/dotnet/roslyn/issues/26029
