### ISSUE TITLE
Fix for : Program does not contain a static 'Main' method

### ISSUE THREAD

**Issue by al-sabr** [FizzerWL/Cs2hx#5]
Hi again I wanted to know how do I apply this fix for the bounty-castle dll library.

I know that the solution is described but I could not understand where and what to delete the specified items.

Can you elaborate more please : https://github.com/dotnet/roslyn/issues/26029#issuecomment-380164421

Reference project : [bounty-castle-1.8.6.zip](https://github.com/FizzerWL/Cs2hx/files/4776420/bounty-castle-1.8.6.zip)

**Comment by FizzerWL** [comment]
The zip file you attached only contains css and javascript files.  It doesn't seem related to a C# converter at all.  It looks like perhaps you attached the wrong file?

Also note that Cs2hx is a C# to Haxe converter.  A dll file does not contain any C#, and therefore cannot be used.  You need raw C# source files to use it.

**Comment by al-sabr** [comment]
How can you say that it contains css and javascript files?

It is only .cs files and not .css files isn't it?
Well tell me that this also contains css and js files please.

Can you then do it yourself with screencasting your steps into a video file and add it in the README.MD so that we can learn how to get rid of this bug and use this ourselves next time?

Actually I am trying to use bounty-castle from Haxe to AS3 as a SWC library.

This is the project file original : https://www.bouncycastle.org/csharp/download/bccrypto-csharp-1.8.6-bin.zip

**Comment by FizzerWL** [comment]
My bad, I extracted the zip file but then opened the wrong folder.  I see the C# code now.  Sorry about that.

I ran this:  Cs2hx.exe "/sln:C:\Users\randy\Downloads\bounty-castle-1.8.6\bounty-castle-1.8.6.sln"

And I did not get the same error as you.  It worked fine on my computer -- at least, I got an error saying that overloaded constructors are not supported, which is expected.

Try the workaround in https://github.com/dotnet/roslyn/issues/26029, when it says "the output folder" it's talking about cs2hx/bin/Debug or cs2hx/bin/Release

**Comment by al-sabr** [comment]
I used Microsoft Visual Studio 2017 can it be because of that?

You mean I should delete the files starting with Microsoft.Build.*.dll?

![image](https://user-images.githubusercontent.com/26530975/84597629-9b615a80-ae65-11ea-845d-a509c4bd0853.png)

**Comment by al-sabr** [comment]
Ok I removed the files and it works but ends up with errors:

```
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [257..2878) Type: ProofOfPossessionSigningKeyBuilder
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Generate() in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 102
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Go(Compilation compilation, String outDir, IEnumerable`1 extraTranslation, String ctorHelperName, HashSet`1 whitelist, Boolean buildFirst) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at Cs2hx.EntryPoint.Main(String[] args) in G:\programming\c#\Cs2hx\trunk\Cs2hx\EntryPoint.cs:line 0
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [257..2878) Type: ProofOfPossessionSigningKeyBuilder
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Generate() in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 102
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
---> (Inner Exception #0) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [257..2878) Type: ProofOfPossessionSigningKeyBuilder
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [2140..8834) Type: PKMacBuilder
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #2) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [204..6977) Type: SecP256K1FieldElement
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #3) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [224..851) Type: InvalidCipherTextException
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #4) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [237..5972) Type: PgpLiteralDataGenerator
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #5) System.Exception: Constructor overloading not supported [742..843) Type: V2Form
   at Cs2hx.WriteConstructor.WriteInstanceConstructor(HaxeWriter writer, ConstructorDeclarationSyntax ctorOpt) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteConstructor.cs:line 64
   at Cs2hx.WriteConstructor.Go(HaxeWriter writer, ConstructorDeclarationSyntax constructor) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteConstructor.cs:line 21
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 54
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #6) System.Exception: Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [127..424) Type: Asn1Exception
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 135
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #7) System.Exception: Constructor overloading not supported [539..670) Type: SecP256K1Point
   at Cs2hx.WriteConstructor.WriteInstanceConstructor(HaxeWriter writer, ConstructorDeclarationSyntax ctorOpt) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteConstructor.cs:line 64
   at Cs2hx.WriteConstructor.Go(HaxeWriter writer, ConstructorDeclarationSyntax constructor) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteConstructor.cs:line 21
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 54
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #8) System.Exception: When catching an Exception, you cannot use the object as an Exception object, since the destination platform supports throwing things that don't derive from Exception.  Instead, call .ToString() on it if you need details of it.  [3710..3711) Method: SetSignatureAlgorithm, Type: X509V2CrlGenerator
   at Cs2hx.WriteTryStatement.Go(HaxeWriter writer, TryStatementSyntax tryStatement) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteTryStatement.cs:line 77
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 118
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteMethod.GoInternal(HaxeWriter writer, BaseMethodDeclarationSyntax method, TypeSyntax returnType, TypeParameterListSyntax typeParameterListOpt, Nullable`1 constraintClassesOpt) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteMethod.cs:line 117
   at Cs2hx.WriteMethod.Go(HaxeWriter writer, MethodDeclarationSyntax method) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteMethod.cs:line 17
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 48
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #9) System.Exception: When catching an Exception, you cannot use the object as an Exception object, since the destination platform supports throwing things that don't derive from Exception.  Instead, call .ToString() on it if you need details of it.  [7929..7930) Method: CopyAndAddExtension, Type: X509V3CertificateGenerator,  [7940..7941) Method: CopyAndAddExtension, Type: X509V3CertificateGenerator
   at Cs2hx.WriteTryStatement.Go(HaxeWriter writer, TryStatementSyntax tryStatement) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteTryStatement.cs:line 77
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 118
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteMethod.GoInternal(HaxeWriter writer, BaseMethodDeclarationSyntax method, TypeSyntax returnType, TypeParameterListSyntax typeParameterListOpt, Nullable`1 constraintClassesOpt) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteMethod.cs:line 117
   at Cs2hx.WriteMethod.Go(HaxeWriter writer, MethodDeclarationSyntax method) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteMethod.cs:line 17
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 48
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #10) System.Exception: Node not in a body
   at Cs2hx.WriteThrowStatement.ReturnsVoid(SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteThrowStatement.cs:line 75
   at Cs2hx.WriteThrowStatement.Go(HaxeWriter writer, ThrowStatementSyntax statement) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteThrowStatement.cs:line 18
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 98
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteIfStatement.Go(HaxeWriter writer, IfStatementSyntax ifStatement, Boolean indent) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteIfStatement.cs:line 28
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 86
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.Core.WriteBlock(HaxeWriter writer, BlockSyntax block) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 165
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 60
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteMethod.WriteIndexerDeclaration(HaxeWriter writer, IndexerDeclarationSyntax decl) in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteMethod.cs:line 318
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 148
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in G:\programming\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---
```

How can I fix this issue?

**Comment by FizzerWL** [comment]
Glad you solved it!

If you are surprised by the error you pasted, it means you likely didn't read the Limitations section.  Overloaded constructors are clearly listed as a feature that's not supported, so, just as the limitations section explains, you have to refactor your code to work around them.

Taking a large, existing project, and running it through cs2hx is not likely to end well. cs2hx is best used when you wrote the code yourself, keeping its limitations in mind.  You should expect to have to spend many hours to do what you're trying to do.

**Comment by al-sabr** [comment]
Ok I understand and where is it mentioned the code that I should modify? Which file should I adapt?

**Comment by FizzerWL** [comment]
Read the first line of the error message:   Haxe does not support overloaded constructors.  Consider changing all but one to static Create methods [257..2878) Type: ProofOfPossessionSigningKeyBuilder

**Comment by al-sabr** [comment]
Can it be possible that this tools rename all the other overloaded constructors into static functions by renaming them with ConstructorName1, ConstructorName2, ConstructorName3, etc ...?

Or not static as normal functions maybe?

Could this be a solution or a similar idea for this error to go away?

**Comment by FizzerWL** [comment]
Sure, it's possible. All of Cs2hx's limitations could be removed with some effort.  Feel free to fork if that's something you want to do.

**Comment by al-sabr** [comment]
So I would ask you which place I should start investigate so that I don't loose my time?

Like any guidance?

Oh boy been a while since I touched C# maybe 15 years...
