### ISSUE TITLE
Having trouble converting a C# project

### ISSUE THREAD

**Issue by samuelh2005** [FizzerWL/Cs2hx#8]
I've been trying to convert [this](https://github.com/MaximumADHD/Roblox-File-Format) into eventually into Java. Since Haxe can be converted into java I tried to use this program to convert it into Haxe first, but I end up getting these errors.
```
samro@DESKTOP-8LRMBMS MINGW64 /e/c#/Roblox-File-Format (main)
$ Cs2hx /sln:RobloxFileFormat.sln /out:haxe
C# to haXe Converter
See https://github.com/FizzerWL/cs2hx for full info and documentation.


Visual Studio intances: Visual Studio Build Tools 2019 -16.11.32126.315 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin, Visual Studio Community 2022 -17.1.32210.238 C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin
Registered visual studio: Visual Studio Community 2022 - 17.1.32210.238

Converting project RobloxFileFormat...
Building...
Parsing...
Parsed in 00:00:00.3920624. Writing out haxe...
Built in 00:00:01.9475550

Exception:
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Cs2hx.WriteProperty.Go(HaxeWriter writer, PropertyDeclarationSyntax property) in E:\c#\Cs2hx\trunk\Cs2hx\WriteProperty.cs:line 84
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 50
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in E:\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in E:\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Generate() in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 102
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in E:\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Go(Compilation compilation, String outDir, IEnumerable`1 extraTranslation, String ctorHelperName, HashSet`1 whitelist, Boolean buildFirst) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at Cs2hx.EntryPoint.Main(String[] args) in E:\c#\Cs2hx\trunk\Cs2hx\EntryPoint.cs:line 128
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Cs2hx.WriteProperty.Go(HaxeWriter writer, PropertyDeclarationSyntax property) in E:\c#\Cs2hx\trunk\Cs2hx\WriteProperty.cs:line 84
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 50
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in E:\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in E:\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Generate() in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 102
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Cs2hx.WriteProperty.Go(HaxeWriter writer, PropertyDeclarationSyntax property) in E:\c#\Cs2hx\trunk\Cs2hx\WriteProperty.cs:line 84
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 50
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in E:\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) System.Exception: Object initialization syntax is not supported. [1651..3537) Type: Property
   at Cs2hx.WriteObjectCreationExpression.Go(HaxeWriter writer, ObjectCreationExpressionSyntax expression) in E:\c#\Cs2hx\trunk\Cs2hx\WriteObjectCreationExpression.cs:line 20
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 80
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 41
   at Cs2hx.WriteField.Go(HaxeWriter writer, SyntaxTokenList modifiers, String name, TypeSyntax type, EqualsValueClauseSyntax initializerOpt) in E:\c#\Cs2hx\trunk\Cs2hx\WriteField.cs:line 48
   at Cs2hx.WriteField.Go(HaxeWriter writer, FieldDeclarationSyntax field) in E:\c#\Cs2hx\trunk\Cs2hx\WriteField.cs:line 17
   at Cs2hx.Core.Factory(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 52
   at Cs2hx.Core.Write(HaxeWriter writer, SyntaxNode node) in E:\c#\Cs2hx\trunk\Cs2hx\Core.cs:line 22
   at Cs2hx.WriteType.Go() in E:\c#\Cs2hx\trunk\Cs2hx\WriteType.cs:line 124
   at Cs2hx.Program.<>c.<Generate>b__10_9(IGrouping`2 type) in E:\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 111
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---
```

The error seems to be made when it tries to write ```haxe/robloxfiles/binaryformat/BinaryRobloxFileChunk.hx``` after line 13, as that file is the only incomplete one.
```haxe
1  package robloxfiles.binaryformat;
2  using StringTools;
3  import system.*;
4  import anonymoustypes.*;
5
6  class BinaryRobloxFileChunk
7  {
8      public var ChunkType:String;
9      public var Reserved:Int = 0;
10     public var CompressedSize:Int = 0;
11     public var Size:Int = 0;
12     public var CompressedData:haxe.io.Bytes;
13     public var Data:haxe.io.Bytes;
14
```

**Comment by FizzerWL** [comment]
Cs2hx only supports up to C# 4.0, since that was the newest version when it
was invented..  It looks like the code you're converting uses
expression-bodied members, which is a C# 6.0 feature, and thus cs2hx barfs
when it encounters it.  You'd have to either re-write the code to not use
this feature or extend cs2hx to support them.

**Comment by samuelh2005** [comment]
Thanks! I remember to use 4.0 next time.
